# -*- coding: utf-8 -*-
"""AirBnB Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-e4rDSstJXFflb1et6_FhRA4SZRlTFg1
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("compressed_data.csv")

df.head(10)

df.columns

"""# **Checking missing values**"""

df.isnull().sum()

df.info()

"""# **Handling Missing Values**"""

df['last review'] = pd.to_datetime(df['last review'], errors='coerce')

df.info()

df.fillna({'reviews per month': 0, 'last review': df['last review'].min()}, inplace=True)

df.dropna(subset=['NAME', 'host name'], inplace=True)

df.isnull().sum()

df.drop(columns=['license', 'house_rules'])

df['price'] = df['price'].astype(str).str.replace('[\$,]', '', regex=True).str.strip().astype(float)
df['service fee'] = df['service fee'].astype(str).str.replace('[\$,]', '', regex=True).str.strip().astype(float)

df.head()

df.drop_duplicates(inplace=True)

df.info()

df.describe()

"""# **Visualization**"""

# What is the distribution of listing prices?

plt.figure(figsize=(10, 6))
sns.histplot(df['price'], bins=50, kde=True, color = 'red')
plt.title('Distribution of Listing Prices')
plt.xlabel('Price $')
plt.ylabel('Frequency')
plt.show()

"""The histogram shows a fairly even distribution of listing price across different price range, indicating no
particular concentration of listings in any specific price range.
The KDE line helps visualize this even spread more clearly,
confirming that the dataset contains listings with a wide variety of prices.

# **Room Type Analysis**
"""

#Room type distribution

plt.figure(figsize=(8, 5))
sns.countplot(x='room type', data=df , color='hotpink')
plt.title('Room Type Distribution')
plt.xlabel('Room Type')
plt.ylabel('Count')
plt.show()

"""# **Neighborhood Analysis**
# **how listings are distributed across different neighborhoods**
"""

plt.figure(figsize= (10,8))
sns.countplot(y ='neighbourhood group', data = df, color = 'lightgreen', order = df['neighbourhood group'].value_counts().index)
plt.title('Distribution of Listings Across Neighborhoods')
plt.xlabel('Count')
plt.ylabel('Neighborhood Group')
plt.show()

"""The count plot shows a clear distribution
of the number of listings across different neighborhood
groups. Manhattan and Brooklyn dominate the listings,
suggesting they are prime locations for Airbnb. Queens,
Bronx, and Staten Island have fewer listings,
indicating less availability or popularity.

# **Price vs. Room Type**
**Visualize the relationship between price and room type**
"""

plt.figure(figsize=(10, 6))
sns.boxplot(x='room type', y='price', hue='room type', data=df, palette='Set1')
plt.title('Price vs. Room Type')
plt.xlabel('Room Type')
plt.ylabel('Price')
plt.show()

"""Price vs. Room Type
The box plot provides a detailed view
of how prices vary across different room types
in the Airbnb dataset. It shows that while
'Shared room' tends to have lower prices, 'Private room',
'Entire home/apt', and 'Hotel room' have higher and more varied price ranges.
This visualization helps in understanding the pricing
dynamics for different types of accommodations on Airbnb.

# **How has the number of reviews change over the time?**
"""

df['last review'] = pd.to_datetime(df['last review'])
reviews_over_time = df.groupby(df['last review'].dt.to_period('M')).size()
plt.figure(figsize=(12, 6))
reviews_over_time.plot(kind='line',color='red')
plt.title('Number of Reviews Over Time')
plt.xlabel('Date')
plt.ylabel('Number of Reviews')
plt.show()

"""The line plot provides a clear visualization
of the number of reviews over time.
It helps identify trends and patterns in review activity,
such as periods of high or low activity.
This information can be useful for understanding
 the dynamics of user engagement and the popularity
of Airbnb listings over time. The significant spikes
and drops in reviews might be worth further investigation
 to understand the underlying causes, such as changes
 in Airbnb policies, market conditions, or external events.

"""